package com.diplom5.Controllers;


import com.diplom5.entity.Role;
import com.diplom5.entity.User;
import com.diplom5.repository.UserRepo;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
@Controller
public class StudentController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepo userRepository;
    @GetMapping(path = "/")
    public String showIndex(){
        return "index";
    }
    @GetMapping(path="/greeting") // Map ONLY GET Requests
    public String addNewUser (@RequestParam (name= "username")String username, Model model
            , @RequestParam String email, @RequestParam String password
            , @RequestParam Role role)
    {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        model.addAttribute("username", username);
        User n = new User();
        n.setUsername(username);
        n.setEmail(email);
        n.setPassword(password);
        n.setRole(role);
        userRepository.save(n);
        return "greeting";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @RequestMapping(value="/registration", method = RequestMethod.POST)
    public String showUsername(@RequestParam String username , @RequestParam String email,
                               @RequestParam String password, @RequestParam Role role){
        return "redirect:/greeting?username="+username+"&email="+email+"&password="+password+"&role="+role;
    }
}