package com.diplom5.Controllers;


import com.diplom5.entity.User;
import com.diplom5.repository.UserRepo;
import com.diplom5.service.UserService;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ResponseBody;
@Controller
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepo userRepository;
    @Autowired
    private UserService userService;

    @RequestMapping(value = "/reg", method = RequestMethod.GET)
    public String showRegistration(Model model) {
        model.addAttribute("user", new User());
        return "registration";
    }
    @RequestMapping(value="/", method = RequestMethod.GET)
    public String homePage(){
        return "greeting";
    }

    @RequestMapping(value="/reg", method=RequestMethod.POST)
    public String processRegistration(User user) {
        userRepository.save(user);
        return "greeting";
    }


    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // @ResponseBody means the returned String is the response, not a view name
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }


    @RequestMapping(value = "/delete/{id}", method = RequestMethod.GET)
    public String deleteById(@PathVariable int id){
        userRepository.deleteById(id);
        return "redirect:/all";
    }
}